name: 'S3 Upload Action'
description: 'A GitHub Action to upload files to AWS S3.'
inputs:
  aws-access-key-id:
    description: 'AWS Access Key ID'
    required: true
  aws-secret-access-key:
    description: 'AWS Secret Access Key'
    required: true
  aws-region:
    description: 'AWS Region'
    required: true
  aws-bucket:
    description: 'S3 Bucket Name'
    required: true
  file-path:
    description: 'Path to the file to upload'
    required: true
  destination-dir:
    description: 'Destination directory in the S3 bucket'
    required: false
  bucket-root:
    description: 'Root directory in the S3 bucket'
    required: false
  output-file-url:
    description: 'Output the file URL'
    required: false
    default: 'true'
  content-type:
    description: 'Content type of the file'
    required: false
  content-disposition:
    description: 'Content disposition of the file'
    required: false
  public:
    description: 'Make the uploaded file public'
    required: false
    default: 'false'
  expire:
    description: 'Expiration time for signed URLs (in seconds)'
    required: false
    default: '180'
  alternative-domain-public:
    description: 'Alternative domain for public files'
    required: false
  alternative-domain-private:
    description: 'Alternative domain for private files'
    required: false
  tags:
    description: 'Comma-separated list of tags for the uploaded file'
    required: false
outputs:
  file-url:
    description: 'The URL of the uploaded file'
  result:
    description: 'Result status: success or failure'
runs:
  using: 'node20'
  main: 'dist/index.js'